package constants

const (
	COLLECTION_CONFIG   = "config"
	KEY_PLAYER_METADATA = "player_metadata"
)

const (
	COLLECTION_ANIMALS = "animals"
)

const (
	ANIMAL_CHICKEN = "chicken"
	ANIMAL_COW     = "cow"
)

const (
	COLLECTION_PLANT_SEEDS = "plant_seeds"
)
const (
	PLANT_SEED_CARROT_SEED = "carrotSeed"
	PLANT_SEED_POTATO_SEED = "potatoSeed"
)

const (
	COLLECTION_REWARDS = "rewards"
)

const (
	COLLECTION_INVENTORIES = "inventories"
)

const (
	TYPE_SEED         = 0
	TYPE_FARMING_TILE = 1
)

const (
	COLLECTION_FARMING_TOOLS = "farming_tools"
)

const (
	FARMING_TOOL_PESTICIDE    = "pesticide"
	FARMING_TOOL_FERTILIZER_1 = "fertilizer1"
	FARMING_TOOL_FERTILIZER_2 = "fertilizer2"
)

const (
	COLLECTION_FARMING_TILES = "FARMING_TILEs"
)

const (
	FARMING_TILE_BASIC_FARMING_TILE_FREE = "basicFARMING_TILEFree"
	FARMING_TILE_BASIC_FARMING_TILE_1    = "basicFARMING_TILE1"
	FARMING_TILE_BASIC_FARMING_TILE_2    = "basicFARMING_TILE2"
	FARMING_TILE_BASIC_FARMING_TILE_3    = "basicFARMING_TILE3"
	FARMING_TILE_PREMIUM_FARMING_TILE_1  = "premiumFARMING_TILE1"
	FARMING_TILE_PREMIUM_FARMING_TILE_2  = "premiumFARMING_TILE2"
	FARMING_TILE_PREMIUM_FARMING_TILE_3  = "premiumFARMING_TILE3"
)
